# Generated by Django 5.0.1 on 2024-01-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default=333445343, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bvn',
            field=models.CharField(default=32345345345, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
