# Generated by Django 5.0.1 on 2024-01-19 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pin', models.CharField(max_length=4)),
                ('limit_level', models.PositiveIntegerField(default=1)),
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('bank', models.CharField(max_length=20)),
                ('bvn', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
