# Generated by Django 4.2 on 2024-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
