# Generated by Django 4.2 on 2024-01-20 05:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(default='~/Desktop/Downloads/pngwing.com.png', max_length=255, verbose_name='image'),
        ),
    ]
